Change build files, gradle wrapper properties and rename cameraview module
team-supercharge/SCCameraView pull request #1
Opened 2017-07-03 14:15 UTC by belanagy

2017-07-03 14:21 UTC, WonderCsabo requested changes

2017-07-03 14:21 UTC, WonderCsabo commented on app/.gitignore
> +*.iml
Two lines are needed here only:
```
/build
*.iml
```

2017-07-03 14:21 UTC, WonderCsabo commented on sccameraview/build.gradle
> +    compile 'com.android.support:appcompat-v7:25.3.1'
This is not needed.

2017-07-03 14:21 UTC, WonderCsabo commented on sccameraview/build.gradle
> +        minSdkVersion 16
14

2017-07-03 14:43 UTC, belanagy commented on app/.gitignore
> +*.iml
done

2017-07-03 14:44 UTC, belanagy commented
Changes applied by your suggestions

2017-07-06 09:13 UTC, WonderCsabo approved these changes

2017-07-06 09:13 UTC, merged