Add record and switch camera features
team-supercharge/SCCameraView pull request #2
Opened 2017-07-06 12:06 UTC by belanagy

Both front and back facing cameras are utilized
Video is recorded and saved on the device's internal storage
Storage path getter is prepared also to provide image directory for later use

2017-07-10 09:26 UTC, WonderCsabo commented on app/src/main/res/values/strings.xml
> +    <string name="main_switch_button">SWITCH</string>
Use lowercase for these strings, the style will uppercase them.

2017-07-10 09:32 UTC, WonderCsabo requested changes

2017-07-10 09:32 UTC, WonderCsabo commented on app/src/main/res/values/strings.xml
> +    <string name="main_switch_button">SWITCH</string>
Use lowercase for these strings, the style will uppercase them.

2017-07-10 09:32 UTC, WonderCsabo commented on app/src/main/res/values/styles.xml
> +        <item name="android:windowNoTitle">true</item>
Instead extend a `NoActionBar` theme.

2017-07-10 09:32 UTC, WonderCsabo commented on app/src/main/res/values/styles.xml
> +        <item name="android:windowFullscreen">true</item>
I do not think we need full screen for this.

2017-07-10 09:32 UTC, WonderCsabo commented on sccameraview/src/main/java/com/example/sccameraview/BaseCameraView.java
> +            if (!(ContextCompat.checkSelfPermission(getContext(), Manifest.permission.WRITE_EXTERNAL_STORAGE) == PackageManager.PERMISSION_GRANTED &&
We do not need permission check in this library, this is the responsibility of the client.

2017-07-10 09:32 UTC, WonderCsabo commented on sccameraview/src/main/java/com/example/sccameraview/Camera2View.java
> +    public void switchCamera() {
An `abstract` method should be for this in the base class, don't you think?

2017-07-10 11:29 UTC, belanagy commented on sccameraview/src/main/java/com/example/sccameraview/Camera2View.java
> +    public void switchCamera() {
There is, implemented in both classes, with different camera release methods

2017-07-10 11:37 UTC, WonderCsabo commented on sccameraview/src/main/java/com/example/sccameraview/Camera2View.java
> +    public void switchCamera() {
Then this method is missing the `@Override` annotation.

2017-07-10 12:06 UTC, belanagy commented on sccameraview/src/main/java/com/example/sccameraview/Camera2View.java
> +    public void switchCamera() {
Indeed! :)

2017-07-11 10:42 UTC, WonderCsabo commented on app/src/main/java/io/supercharge/sccameraview/MainActivity.java
> +            bindViews();
You can bind the views without permission. The only thing is when you open the camera, everything else can be written outside of the `if`.

2017-07-11 10:45 UTC, WonderCsabo requested changes

2017-07-11 10:45 UTC, WonderCsabo commented on sccameraview/build.gradle
> +    compile "com.android.support:support-core-utils:25.3.1"
We do not need this.

2017-07-11 10:45 UTC, WonderCsabo commented on sccameraview/src/main/java/com/example/sccameraview/BaseCameraView.java
> +    public abstract void switchCamera();
We should also have a setter or attribute, which sets the used camera up-front.

2017-07-11 10:45 UTC, WonderCsabo commented on sccameraview/src/main/java/com/example/sccameraview/Camera2View.java
> +    private File getOutputMediaFile(int type){
Why do we need this method exaclty? The client should be able to decide where to save the file.

2017-07-11 11:45 UTC, belanagy commented on sccameraview/src/main/java/com/example/sccameraview/BaseCameraView.java
> +    public abstract void switchCamera();
camera is opened based on frontFacingCameraActive attribute, which is set true in the constructor, is that a bad practice?

2017-07-11 11:47 UTC, belanagy commented on sccameraview/src/main/java/com/example/sccameraview/Camera2View.java
> +    private File getOutputMediaFile(int type){
it is supposed to be a temporary solution to be able to test recording and taking a photo. File is saved based on which function was called

2017-07-11 14:08 UTC, WonderCsabo commented on sccameraview/src/main/java/com/example/sccameraview/BaseCameraView.java
> +    public abstract void switchCamera();
It is okay, just add a setter to it, so if the client wants back-facing, currently he must open the normal camera and then switch to back. He should be able to just open the back camera in the first place, by setting that.

2017-07-11 14:09 UTC, WonderCsabo commented on sccameraview/src/main/java/com/example/sccameraview/Camera2View.java
> +    private File getOutputMediaFile(int type){
So this method will be removed later? I am confused.

2017-07-11 14:45 UTC, belanagy commented on sccameraview/src/main/java/com/example/sccameraview/Camera2View.java
> +    private File getOutputMediaFile(int type){
Yes, I plan to do a refactor on this

2017-07-11 14:45 UTC, WonderCsabo commented on sccameraview/src/main/java/com/example/sccameraview/Camera2View.java
> +    private File getOutputMediaFile(int type){
Okay.

2017-07-12 07:38 UTC, belanagy commented on sccameraview/src/main/java/com/example/sccameraview/BaseCameraView.java
> +    public abstract void switchCamera();
Done and updated

2017-07-12 11:37 UTC, WonderCsabo approved these changes

2017-07-12 11:37 UTC, merged