Add snapshot feature
team-supercharge/SCCameraView pull request #8
Opened 2017-07-17 15:00 UTC by belanagy

2017-07-18 07:32 UTC, WonderCsabo requested changes

2017-07-18 07:32 UTC, WonderCsabo commented on app/src/main/java/io/supercharge/sccameraview/MainActivity.java
> +    private Button snapButton;
This is rather vague. I would call this everywhere `takePictureButton`.

2017-07-18 07:32 UTC, WonderCsabo commented on sccameraview/src/main/java/com/example/sccameraview/Camera2View.java
> +                                    startPreview();
I do not think we want to automatically start the preview. Instead, we should create a callback, which will notify the client if set.

2017-07-18 07:32 UTC, WonderCsabo commented on sccameraview/src/main/java/com/example/sccameraview/Camera2View.java
> +                                CaptureRequest.CONTROL_AF_MODE_OFF);
Autofocus and flash should be controlled by the client, buy using boolean setters.

2017-07-18 07:32 UTC, WonderCsabo commented on sccameraview/src/main/java/com/example/sccameraview/Camera2View.java
> +        imageReader = ImageReader.newInstance(previewSize.getWidth(), previewSize.getHeight(), ImageFormat.JPEG, 1);
We should not use the preview size here. We could reuse how we choose the video size.

2017-07-18 07:32 UTC, WonderCsabo commented on sccameraview/src/main/java/com/example/sccameraview/Camera1View.java
> +        camera.takePicture(null, null, null, new Camera.PictureCallback() {
What is the image size here? What about flash and autofocus?

2017-07-18 07:32 UTC, WonderCsabo commented on sccameraview/src/main/java/com/example/sccameraview/BaseCameraView.java
> +                FileOutputStream fos = new FileOutputStream(pictureFile);
We cannot save the image on the UI thread.

2017-07-18 14:38 UTC, belanagy commented on sccameraview/src/main/java/com/example/sccameraview/Camera1View.java
> +        camera.takePicture(null, null, null, new Camera.PictureCallback() {
Size, flash, and autofocus are set when the camera is opened, the camera1 API callbacks work with those values.

2017-07-18 14:38 UTC, belanagy commented on sccameraview/src/main/java/com/example/sccameraview/Camera2View.java
> +        imageReader = ImageReader.newInstance(previewSize.getWidth(), previewSize.getHeight(), ImageFormat.JPEG, 1);
The video and preview sizes are chosen basically by the same algorithm after you look at it several times, with the next feature it is unified and only one method is called. 
Please elaborate on why this should not be used. 
I've updated the code based on the other suggestions

2017-07-18 14:45 UTC, WonderCsabo commented on sccameraview/src/main/java/com/example/sccameraview/Camera1View.java
> +        camera.takePicture(null, null, null, new Camera.PictureCallback() {
Okay.

2017-07-18 14:47 UTC, WonderCsabo commented on sccameraview/src/main/java/com/example/sccameraview/Camera2View.java
> +        imageReader = ImageReader.newInstance(previewSize.getWidth(), previewSize.getHeight(), ImageFormat.JPEG, 1);
The preview size matches the size of the displayed view. However in most cases, the user wants to create a much bigger size for the actual image. The preview size is under full HD, but the actual image should be 12 megapixels (just an example).

2017-07-19 13:09 UTC, WonderCsabo requested changes

2017-07-19 13:09 UTC, WonderCsabo commented on sccameraview/src/main/java/com/example/sccameraview/BaseCameraView.java
> +        SaveImageRunnable saveImageThread = new SaveImageRunnable();
This is not a thread but a runnable. And this way it will not run on a separate thread.

2017-07-20 08:24 UTC, belanagy commented on sccameraview/src/main/java/com/example/sccameraview/BaseCameraView.java
> +        SaveImageRunnable saveImageThread = new SaveImageRunnable();
AsyncTask implemented

2017-07-20 08:55 UTC, WonderCsabo requested changes

2017-07-20 08:55 UTC, WonderCsabo commented on sccameraview/src/main/java/com/example/sccameraview/SaveImageTask.java
> +        imageSavedListener.onImageSaved();
It is possible the user set `null` to this.

2017-07-20 08:55 UTC, WonderCsabo commented on sccameraview/src/main/java/com/example/sccameraview/SaveImageTask.java
> +    private byte[] imageData;
We should pass all parameters in the constructor, and make these fields `final`.

2017-07-20 09:06 UTC, belanagy commented on sccameraview/src/main/java/com/example/sccameraview/SaveImageTask.java
> +    private byte[] imageData;
Ok

2017-07-20 09:06 UTC, belanagy commented on sccameraview/src/main/java/com/example/sccameraview/SaveImageTask.java
> +        imageSavedListener.onImageSaved();
it is always initialized in the base constructor

2017-07-20 09:14 UTC, WonderCsabo commented on sccameraview/src/main/java/com/example/sccameraview/SaveImageTask.java
> +        imageSavedListener.onImageSaved();
I am confused. We introduced this listener so the user can set arbitrary action after the image is taken. But now i do not even see the setter for that listener.

2017-07-20 09:17 UTC, belanagy commented on sccameraview/src/main/java/com/example/sccameraview/SaveImageTask.java
> +        imageSavedListener.onImageSaved();
oh okay, yes I get that, so there should only be a default action when this field is null

2017-07-20 09:18 UTC, WonderCsabo commented on sccameraview/src/main/java/com/example/sccameraview/SaveImageTask.java
> +        imageSavedListener.onImageSaved();
Yes.

2017-07-20 10:59 UTC, belanagy commented on sccameraview/src/main/java/com/example/sccameraview/SaveImageTask.java
> +        imageSavedListener.onImageSaved();
Ok

2017-07-21 13:12 UTC, WonderCsabo approved these changes

2017-07-21 13:13 UTC, merged