Add device based aspect ratio selection
team-supercharge/SCCameraView pull request #9
Opened 2017-07-31 12:14 UTC by belanagy

2017-08-02 10:54 UTC, richardradics commented on sccameraview/src/main/java/io/supercharge/sccameraview/AspectRatio.java
> +    public String getRatioSize() {
?

2017-08-02 10:54 UTC, richardradics commented on sccameraview/build.gradle
> +    compile 'com.android.support.constraint:constraint-layout:1.0.2'
do we need this dependency in the lib?

2017-08-02 10:54 UTC, richardradics commented on sccameraview/src/main/java/io/supercharge/sccameraview/AspectRatio.java
> +    private int gcd;
gcd? i would give a more understandable fieldname

2017-08-02 10:54 UTC, richardradics commented on sccameraview/src/main/AndroidManifest.xml
>           android:label="@string/app_name"
remove label, support rtsl

2017-08-02 10:54 UTC, richardradics commented on sccameraview/src/main/java/io/supercharge/sccameraview/AspectRatio.java
> +    private static int gcd(int a, int b) {
more understandable name pls

2017-08-02 10:58 UTC, richardradics commented on sccameraview/src/main/java/io/supercharge/sccameraview/Camera1View.java
> +            e.printStackTrace();
remove this, use `Log.e(LOG_TAG, e.getMessage());`

2017-08-02 10:59 UTC, richardradics commented on sccameraview/src/main/java/io/supercharge/sccameraview/Camera1View.java
> +            e.printStackTrace();
remove this, use: `Log.e(LOG_TAG, e.getMessage());`

2017-08-02 10:59 UTC, richardradics commented on sccameraview/src/main/java/io/supercharge/sccameraview/Camera2View.java
> +            e.printStackTrace();
remove this, use `Log.e(LOG_TAG, e.getMessage());`

2017-08-02 11:00 UTC, richardradics commented on sccameraview/src/main/java/io/supercharge/sccameraview/Camera2View.java
> +            e.printStackTrace();
remove this, use `Log.e(LOG_TAG, e.getMessage());`

2017-08-02 11:00 UTC, richardradics commented on sccameraview/src/main/java/io/supercharge/sccameraview/Camera2View.java
> +            e.printStackTrace();
remove this, use `Log.e(LOG_TAG, e.getMessage());`

2017-08-02 11:00 UTC, richardradics commented on sccameraview/src/main/java/io/supercharge/sccameraview/Camera2View.java
> +            e.printStackTrace();
remove this, use `Log.e(LOG_TAG, e.getMessage());`

2017-08-02 11:00 UTC, richardradics commented on sccameraview/src/main/java/io/supercharge/sccameraview/Camera2View.java
> +            e.printStackTrace();
remove this, use `Log.e(LOG_TAG, e.getMessage());`

2017-08-02 11:00 UTC, belanagy commented on sccameraview/src/main/java/io/supercharge/sccameraview/Camera1View.java
> +            e.printStackTrace();
removed logs and unnecessary dependencies

2017-08-02 11:00 UTC, richardradics commented on sccameraview/src/main/java/io/supercharge/sccameraview/Camera2View.java
> +            e.printStackTrace();
remove this, use `Log.e(LOG_TAG, e.getMessage());`

2017-08-02 11:00 UTC, richardradics commented on sccameraview/src/main/java/io/supercharge/sccameraview/SaveImageTask.java
> +                e.printStackTrace();
remove this, use `Log.e(LOG_TAG, e.getMessage());`

2017-08-02 11:00 UTC, richardradics commented on sccameraview/src/main/java/io/supercharge/sccameraview/SaveImageTask.java
> +                e.printStackTrace();
remove this, use `Log.e(LOG_TAG, e.getMessage());`

2017-08-02 14:17 UTC, WonderCsabo requested changes

2017-08-02 14:17 UTC, WonderCsabo commented on app/build.gradle
> +buildscript {
These are already declared in the top-level project.

2017-08-02 14:17 UTC, WonderCsabo commented on sccameraview/build.gradle
> +buildscript {
Again, these are already in the root project.

2017-08-03 15:52 UTC, WonderCsabo approved these changes

2017-08-03 15:53 UTC, merged